### ISSUE TITLE
Switch Right for Left Click

### ISSUE THREAD

**Issue by Wdavery** [Mortennn/Dozer#10]
A Dozer users primary objective is to toggle the menu items, so I think that action should follow the primary click; a left click. And make preferences a right click, or secondary action.

**Comment by Mortennn** [comment]
Thanks for your suggestions! I really appreciate the feedback👍 I am currently working on a big update for Dozer, so there might go some time (about 2 weeks) before I will begin working on these enhancements.

**Comment by Wdavery** [comment]
Oh good I was hoping you wouldn’t be like “who’s this guy spamming the issues” haha
I really like the app in its current state. 
I was using Vanilla https://matthewpalmer.net/vanilla/ previously, and wasn’t really happy with it. 
I think this will blow it out of the water! 


<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Mortennn** [comment]
Thank you for the kind words!

**Comment by halo** [comment]
@Mortennn I am *extremely* grateful that you created this app. I found it accidentally [over here](https://github.com/serhii-londar/open-source-mac-os-apps/commit/2ecbaf776520fb0a6e52208e7caadfc7153d94c3). In fact, I was going to create this application myself had you not done it :) I've been looking for an open-source alternative for menu bar minimalism for some time.

I envisioned it in a way that a simple hover would reveal and hide the menu bar items. I never got to the details, but I was imagining that dozer, when it is hiding the other items, takes on such a large horizontal space (invisibly) that it can react to hover actions.

There may be technical reasons why this is not possible. But I thought I'd suggest it in this issue - because neither left nor right click are the most intuitive solution I can think of (another side-note: with hover, there would maybe be no need for a dozer application icon in the menu bar at all).

Again, thank you for your efforts. I'm sure I'll check out your project regularly :)

**Comment by Mortennn** [comment]
Really nice idea! Technically, I think it is possible. At least I have one idea to how it could be achieved.
I am currently rewriting the project, but afterwards, I will definitely look into how to implement the hover effect.

**Comment by redlegend96** [comment]
Would it be possible to maybe have the menu with the hidden apps collapse after a few seconds if it is not used? I think it would work well visually

**Comment by halo** [comment]
@Mortennn Beautiful! And thank you again for a brand new app :) I'm amazed the hover works splendidly. For what it's worth, there should probably be an option to auto-hide the icons after a few seconds so I don't have to manually hide them again. But this is 99% of what I need, so I'm happy already :)

**Comment by Mortennn** [comment]
Thank you! I will create a new issue for the auto-hide feature.

**Comment by tatecapone** [comment]
Only the icons should be displayed when clicking on the application icon again. Excellent App !! I love It

**Comment by Mortennn** [comment]
I'm glad you like the app😀 I am not sure I understand your suggestion. Can you please elaborate? :)

**Comment by tatecapone** [comment]
I say that it would be nice if the hidden icons could only be seen when
clicking on dozer again and not just putting the mouse cursor over the menu
bar. Felicidades, neither bartender nor vanilla work so well. FiScript is
AWESOME too!
😎

**Comment by Mortennn** [comment]
Ah, I see. I will create a new issue for this feature too. And thanks again - it is nice to know that you enjoy the app😀

**Comment by tatecapone** [comment]
;)

**Comment by tatecapone** [comment]
👏🥳🥳 Mortenn you Rocks!!

**Comment by tatecapone** [comment]
Mortenn good update...you Rocks!!!
📣📣😉
