### ISSUE TITLE
explain the 2nd dot

### ISSUE THREAD

**Issue by flypenguin** [Mortennn/Dozer#113]
love dozer. really do.

i just don't get why there have to be TWO dots ... ?!

**Comment by AlbertVilaCalvo** [comment]
If you place the 2 dots together then it doesn't do anything. But if you have some icons in between the 2 dots, then the left dot sets the point in which the icons to it's left will appear/disappear when click on the right dot.

This wat you can show/hide the icons on the left of the 2nd dot quickly while keeping the icons on the right always visible.

**Comment by flypenguin** [comment]
yeah. or you could just NOT have the 2nd dot and place the now only dot where you want to start hiding.

basically my toolbar looks like this - and I would be very interested in who does it differently, and most importantly WHY:

<img width="162" alt="grafik" src="https://user-images.githubusercontent.com/5030694/83951609-d4c91300-a832-11ea-9f4e-600a591dea26.png">

**Comment by AlbertVilaCalvo** [comment]
For me it works well now as it is. I actually like how it works.

**Comment by flypenguin** [comment]
good for you 😆 . still that was not the question.

**Comment by lisachev** [comment]
>  who does it differently, and most importantly WHY:
> 

You can put the second dot somewhere else. I put it closer to the corner to make mouse approach easier. This way everything to the left of left dot gets hidden when I click the right dot. The right dot stays at the second from the right spot.

**Comment by FezVrasta** [comment]
Could the second dot disappear when the two dots are next to eachother?

**Comment by flypenguin** [comment]
perfect idea!!
Am 26. Juni 2020, 13:05 +0200 schrieb Federico Zivolo <notifications@github.com>:

**Comment by gingerbeardman** [comment]
If the 2nd dot disappeared then how would you get it back or how would you know where the middle area is when you want to put an icon there?

**Comment by FezVrasta** [comment]
Make it an option? It's clear a lot of people here don't like this second dot, since the most common use case is to have them next to each other.

**Comment by gingerbeardman** [comment]
There is a workaround

![Screen shot 2020-07-03 at 12 49 16](https://user-images.githubusercontent.com/49612/86466480-9c323180-bd2b-11ea-9d13-9b02f883c7b0.png)

- alt-click dot
- you now see remove area
- drag unwanted second dot to remove area
- click dot to hide remove area

**Comment by flypenguin** [comment]
@gingerbeardman if I get this correctly this is a different use case and not a workaround. since "all left of the dot" is hidden - if I move the unwanted dot next to the hidden dot, I also have to move all the "hide me" icons into the "permanently removed" icon area.

if you get what I mean.

so no, I don't see it, and I wholeheartedly agree with @FezVrasta  to make this an option :)

**Comment by gingerbeardman** [comment]
I see what you mean, yes this isn't a workaround for what you want. Sorry :)

**Comment by FezVrasta** [comment]
I thought about something, if the two dots collapsed when next to each other, you could make them expand if you drag the single remaining dot while pressing a combination of keys

**Comment by gingerbeardman** [comment]
Read more about this in #54

**Comment by FezVrasta** [comment]
I understand but most of the people don't need it

**Comment by gingerbeardman** [comment]
Some people, not most people

**Comment by ndbroadbent** [comment]
Hello, sorry can you please re-open this issue? #122 did not add an option to remove the second dot. I also find this a little bit annoying and would like the option to just show a single dot.

**Comment by ndbroadbent** [comment]
Argh sorry I didn't realize how difficult this would be! I forked the project and tried to add a new option for this, but I can see why this is so difficult now. Here's my branch with the attempted changes: https://github.com/ndbroadbent/Dozer/tree/single-dot

It turns out that the second dot (on the left) is actually how Dozer works - this dot gets expanded to a really long width and disappears while pushing all of the other items off the screen. And due to the way that dots can be dragged around on the status bar, it's extremely difficult to only use one dot.

I almost got a proof of concept working where I tried to make one of the dots invisible and just use the other one. I set `statusIconButton.imagePosition` to `.imageRight` (or `.imageTrailing`), and this almost works. But then once the width is too large, both of the dots disappear, so you can't show the icons anymore (unless you use a shortcut key.)

![single-dot-brokenSep-27-2020 19-00-28](https://user-images.githubusercontent.com/139536/94363347-41269580-00f4-11eb-8a66-597b23c8b6b1.gif)

So maybe this is the reason why this hasn't been added yet? (Unless I'm missing something!) Although apparently there was an older version that did work using just one dot, so maybe I have to dig through the commit history and figure out how that worked.

**Comment by huyz** [comment]
That's a funny hack.
It is a bit disingenuous to omit an explanation of how this implementation detail "leaks" into the UX.  If the README clearly explained that the second dot is there for implementation reasons, users would more readily accept the compromise to the UX.

**Comment by FezVrasta** [comment]
At least allow to set the second dot icon to a transparent one so that it only shows up as a white space?

**Comment by ndbroadbent** [comment]
@FezVrasta I tried that too, and also tried setting the width to 0px. The main problem is that both of the dots are interchangeable, and the app doesn't have any ability to control the order of the dots in the status bar. This is all handled by the operating system, so when you drag the main dot to a new position, it's not possible to write some code that also updates the position of the invisible dot. This is all handled by the OS, including remember the position of the dots when you quit and restart the app. 

I guess it would work, but you have to remember to always drag the invisible dot to the left of the main dot whenever you change the position. I think it would be a weird user experience and cause some confusion for new users, but maybe it's fine if it's explained properly

**Comment by gingerbeardman** [comment]
Post up a build so we can try it?

**Comment by rcnza** [comment]
Its been months and I still just don't understand the use of a second dot at all.  The absolute only way to use dozer seem to be to have the 2 dots next to each other, so maybe the idea of making the left dot transparent or a "space" character has merit?  I mean, if you want to keep some icons visible, just keep them to the right of the right dot?  The dot should surely only be there to hide stuff that you don't want to see?

**Comment by gingerbeardman** [comment]
> The absolute only way to use dozer seem to be to have the 2 dots next to each other, 

Nonsense. Case in point: I don't use it like this. 

It's easy:
1. Everything to the left of the left dot will be hidden. This allows fine control. 
2. The right dot you are free to position where you want in your visible icons. This is the trigger to toggle the hidden icons. 

Of course, you can position the two dots next to each other - which might make it feel like there should only be one dot - but many of us position the dots far from each other. 

Also, don't forget you can use a hotkey instead of clicking the trigger dot. 

> Edit: maybe another approach will work: instead of 2 identical dots, give each dot a different icon, so its easier to understand/appreciate the difference/impact of the dots?

I believe there's a PR proposing a similar change.

**Comment by FezVrasta** [comment]
Considered how much confusion the two dots produce I would evaluate if they are worth to exist. It's logical for the user to click on the far left of the menu bar to show more icons, showing more icons clicking on an icon on the opposite side of the menu bar doesn't just make sense from a user experience standpoint.

**Comment by rcnza** [comment]
>     1. Everything to the left of the left dot will be hidden. This allows fine control.
> 
>     2. The right dot you are free to position where you want in your visible icons. This is the trigger to toggle the hidden icons.

This perfectly highlights the confusion.  There is no need for the right dot.  Since everything from the absolute right of the monitor up to the position of the left dot _Will_ be visible, regardless of the position of the right dot???

**Comment by gingerbeardman** [comment]
> Considered how much confusion the two dots produce I would evaluate if they are worth to exist. 

They are needed for the app to function as it does. See ndbroadbent explanation above.

> showing more icons clicking on an icon on the opposite side of the menu bar doesn't just make sense from a user experience standpoint.

This is actually how I use Dozer, I find it easier to move my mouse button into the corner of the screen - it's a much easier target to hit than a small dot in the middle of the screen.

<img width="1080" alt="Screen shot 2020-10-02 at 11 50 22" src="https://user-images.githubusercontent.com/49612/94915828-7b51b780-04a5-11eb-8824-a38e4ddd2cd4.png">

>  There is no need for the right dot.

There is, because that's how Dozer has been designed to work (see explanation by ndbroadbent above). The left dot it resized so that everything to the left of it is pushed off screen, so the left (or only dot) cannot be used as the trigger dot.

Are you having a similar discussion with the competing apps?

**Comment by gingerbeardman** [comment]
@rcnza here's a partial list of competing or complementary apps, as I was not actually referring to _Vanilla_ but rather _Hidden_. 

- https://github.com/dwarvesf/hidden
- https://www.macbartender.com
- https://github.com/artginzburg/barhide (CLI; I use this to hide Notification Center icon)
- https://matthewpalmer.net/vanilla/

**Comment by FezVrasta** [comment]
> This is actually how I use Dozer, I find it easier to move my mouse button into the corner of the screen - it's a much easier target to hit than a small dot in the middle of the screen.
> 
> > <img alt="Screen shot 2020-10-02 at 11 50 22" width="1080" src="https://user-images.githubusercontent.com/49612/94915828-7b51b780-04a5-11eb-8824-a38e4ddd2cd4.png">
> 
> Above is how my screen looks.

So you first need to move your mouse to the far right, and then, once the new icons appear, move the mouse to the far left...

**Comment by gingerbeardman** [comment]
Let's not be facetious. 

In terms of Human Interface Design an easy to click target is the most important thing. So positioning it along an edge is good, but a corner is better as it's not possible to move the mouse too far because it stops in the corner. This is how it's thought of at Apple, I know because I worked there on this stuff.

You're quite right that clicking the newly visible icon needs a bit more work in terms of positioning your mouse precisely. But because of the corner trick I only need to do a careful click once, whereas your approach needs two careful clicks.

Also, I hide icons because they are rarely used so I don't use the Dozer dots very often. Maybe once a week?
