### ISSUE TITLE
Dozer Circle disappear after using the setted shortcut

### ISSUE THREAD

**Issue by rodnem** [Mortennn/Dozer#14]
I've set as shortcut : Ctrl+Alt+cmd+F12 (laptop).
But when I use it the Dozer circle is no more visible.
Here is a little screencast:  https://cl.ly/a589aa040751

About the circle, I like its simplicity but… It's to big when closed.
As a designer, I suggest you two solutions:
→ Inverse the 2 circles :    ￮ Closed      ○ Open
    so you can use the wider one when we have opened the circle
→ Use a filled circle for closed :    ● Closed      ○ Open
    It's like you filled the circle with apps that's why it's full
I think it make sens 😄

**Comment by Mortennn** [comment]
Actually, it was meant to be more minimalistic because when you use a shortcut you don't need an icon. But now that I think about it, it should be stated in the boarding screen, to make the user aware of it. Or create an option in the settings, which I think would be the better option. Also, I think I like the "inverse the 2 circles"-solution more because it gives a more minimalistic look. 
Thanks for your feedback!
