### ISSUE TITLE
Icon disappears when menu bar is hidden

### ISSUE THREAD

**Issue by EdenSG** [Mortennn/Dozer#27]
I've reverted to 1.1.3 because the 2.x versions hide the circle when Dozer is hiding the menu bar. Could this be an option?

**Comment by Mortennn** [comment]
The reason why the Dozer icon has been removed in version 2.x is because it caused too many bugs (Just take a look at some of the closed issues). I am planning on bringing it back, but I haven't found a consistent way of doing it yet. In my opinion, not having an icon and just clicking the menu bar, is a much better and cleaner way.
![skaermoptagelse 2018-10-29 kl 17 18 54](https://user-images.githubusercontent.com/34214574/47664240-eea66c80-db9e-11e8-92a3-03bd51129fa7.gif)

**Comment by EdenSG** [comment]
I see. No worries, I'm happy to wait — I'll play with the code as well. I prefer to think of the control as a toggle rather than separate "show" and "hide" actions, but I understand where you're coming from too.
