### ISSUE TITLE
Source code has been removed

### ISSUE THREAD

**Issue by jamieweavis** [Mortennn/Dozer#35]
First of all, thanks for creating Dozer - it's by far the best, free, open-source solution to a messy menu bar that I've found 👍 

One of the great things about Dozer is that it's open-source! But with the latest update `v2.2.0` the source code has been removed from the repository which is slightly worrying from a security standpoint, especially since the application requires elevated accessibility privileges.

Just wanted to let you know that this looks like a red flag to me, and that I (and probably many others) will avoid upgrading the application until the source code has returned.

**Comment by Jackymancs4** [comment]
This is indeed a valid concern. The author address it in the changelog:
> I have decided to only publish the compiled app for now. I will share the codebase later on, when it is more organized, so people actually can understand how the code works, and eventually help to develop the app. It takes time to keep the code synced with Github, and I would rather use that time developing the app.

So, it seems a temporary, understandable situation. Just saying for the records.

**Comment by Mortennn** [comment]
I am aware of that, but it is just way easier to only keep track of one version of the app (I also explain this in the release notes [here](https://github.com/Mortennn/Dozer/releases/tag/2.2.0)).

I am planning to share the source code again, but I want the project to be more organized. Also, I have been leaking the credentials for my Crashlytics account, because I forgot to remove them before publishing. I also want this process to be automated, before publishing the code again.

Regarding the security part: If you have some suggestions on how I can prove that I am not putting some malicious code in the app, please let me know. Dozer is also signed with a valid developer account (not sure if that actually makes the app more trustworthy).

**Comment by jamieweavis** [comment]
I saw the release notes but I still don't understand the need to remove the source code. It just seems suspect to me to remove all source code for a new version in a project which has a decent following.

> I am planning to share the source code again, but I want the project to be more organized.

If you want to discourage people from contributing while you tidy up the project you could put a notice in the README or maybe utilise a [contributing.md](https://help.github.com/articles/setting-guidelines-for-repository-contributors/#adding-a-contributing-file) file to let people know that you aren't currently accepting contributions.

> Also, I have been leaking the credentials for my Crashlytics account, because I forgot to remove them before publishing.

I'm not a Swift developer, nor am I familiar with Crashlytics but isn't this something that you can add to your `.gitignore`?

**Comment by Mortennn** [comment]
I am sorry that this could look like I am trying to do something suspicious because I am really not. There's just a lot of manual things I have to do every time I publish a new version, so I just wanted to make the process easier, and only have to maintain one version of the project. The unorganised project and the leaked credentials were just examples, there are obviously more things to be done than just those.

It's only a hobby project that I'm working on in my spare time, so right now it just doesn't make sense to me to spend time on having the project open source. You can still find the source code for previous versions under releases. I just removed the code from the main repository to not make any confusion about the code of the new versions being unpublished.

I hope this answered your questions/concerns. And I forgot to thank you for the kind words about the project👍

**Comment by jamieweavis** [comment]
No worries, hope you can see my point. Keep up the great work by the way, love the app! :smile:

**Comment by SpongeBobSun** [comment]
Sorry to bother you lot but I don't think it's necessary to remove source code form this repo due to you are refactoring or re-architecture this app.

There are a lot of crappy code & repos on GitHub (including some of my own repos). It's nice to let people see how you refactor & re-organizing your app and they will actually learn something more important than how does the existing code work from the whole refactoring process.

BTW nice work on Dozer.

**Comment by NathanBlais** [comment]
I would also like an update of when we can see the source code returning. No rush since it is your work. :)

**Comment by gingerbeardman** [comment]
I was about to jump in and make a change, but there's no code?

I can find a copy in a fork from a PR, so I'll use that... for now.

**Comment by micahstubbs** [comment]
@gingerbeardman curious, what fork did you end up basing your improvement on.  I would like to collaborate on an open fork.

**Comment by gingerbeardman** [comment]
@micahstubbs  this one: https://github.com/neatlife/Dozer

**Comment by micahstubbs** [comment]
@gingerbeardman nice!  I've made a ninja fork based on https://github.com/neatlife/Dozer

https://github.com/micahstubbs/open-dozer

contributions are welcome.

**Comment by gingerbeardman** [comment]
@micahstubbs I think first job would be to figure out all features/changes since that fork if we can

**Comment by micahstubbs** [comment]
@gingerbeardman would appreciate help figuring out that feature diff.  I hope to have a build of open-dozer published soon.  issues are welcome here https://github.com/micahstubbs/open-dozer/issues

**Comment by Mortennn** [comment]
Sorry for not responding. Dozer will once again be open source.

The source code will be released within a few days. It has been a while since I have last worked on Dozer so I have to clean a few things up and finish some features before publishing.

New features in the source code includes following:
* ”Remove”-icon. Additional icon to hide/show icons with `option+click`
* Auto-hide status bar icons #22
* ”No Icon”-mode. Hide/show only using keyboard shortcut

The source code also includes a new UI in preferences and a new welcome screen.

@micahstubbs @gingerbeardman Thanks for your interest in Dozer! Once the source code is released, I hope we can collaborate on the project😀

**Comment by micahstubbs** [comment]
That's good to hear!  As you can see, there's a community of friendly users that would like to contribute 😄

**Comment by gingerbeardman** [comment]
Fantastic news! All the best to you Mortenn

**Comment by Mortennn** [comment]
Source code is now back.

Checkout [CONTRIBUTING.md](https://github.com/Mortennn/Dozer/blob/master/CONTRIBUTING.md#getting-started) on how to build Dozer.
