### ISSUE TITLE
how to delete it from the Mac system?

### ISSUE THREAD

**Issue by Albeppo** [Mortennn/Dozer#95]
After installation I can see the dots in menu bar on the far left but no icons can be grouped right of  the dots. I might be missing something but since it is not intuitive for me I quit the app and tried to delete them from my system. There is only one folder for dozer, but not in the applications folder. What do I need to do to delete the app?

**Comment by johsoderi** [comment]
I don't know much about this app (came here just now to try it out, lol), but I'll give it a shot since it's gone unanswered for a couple days. I want to point out though, that while this answer might be below your level, it's not unheard of for a question like this to find its way to the top of a search page some day. So it's more general advice than exclusively an answer to your exact question :)

I assume (since you don't have an app in your `/Applications` folder) that you installed it from Terminal with `brew cask install dozer`?
In that case, I would first try to run `brew cask uninstall dozer`.
I'm not sure it'd be successful if you've already deleted some stuff manually, but it's the standard route. 
If that fails, `brew cask zap dozer` should delete any and all files associated with the cask.

If I assumed wrong and you installed by dragging the app to `/Applications`, and you've since deleted it but still see stuff on the screen, then a reboot would be my first action.

If it's still there after a restart, I'd say it's time to open `/Applications/Utilities/Activity Monitor.app` and find out what process is actually left running. Because if it's running, it's in that list. Put the name in the search box and see where it gets you. The names of processes often differs from the app names though, so try searching for smaller parts of the name. If you find something similar but it's unclear if they're actually related, a google search for 'macos process weirdname' will likely give you an answer. Throwing in 'activity monitor' in the search might also help.

If you get nothing, try reversing the search, like 'appname macos process [activity monitor]'. Others might have had related issues before.

When you've found a suspect process, you'll want to know what executable file started that process. It should be noted here that while we're used to consider anything ending with '.app' as an actual program in the Mac world, in 'reality' (to the OS) an .app is merely a folder which contains a 'Unix executable' file, along with resources and metadata. This executable is the one starting the actual process seen in Activity Monitor, or in Terminal with `ps` (`ps -e` to list the current user's processes). They don't need to be in a fancy .app but can be ran from anywhere without showing up in either the Dock or the `cmd-opt-esc` 'Force quit' list. There is more to an .app than a pretty icon and localised name, but I think Apple's abstraction of the relationship between apps and processes was the wrong route, as it makes it hard for the end user to get even a basic understanding of what their computer is doing half the time. And how to get rid of an application that doesn't care that you already deleted it...

Anyway, you've found your process in Activity Monitor, and you want it to die. Preferably painfully?

You select the line, click the gear wheel icon, choose 'sample process', and after a few seconds you will see a bunch of text. The fifth line of that text block contains the path of the file that started the process, and might look something like this:
`/SomeFolder/Perhaps/Some/Subfolders/theculprit`

Copy the path and close the Sample window. Now you could go directly to Finder, press shift-cmd-g,  cmd-v and enter to go to the parent folder of the executable, then just drag the file in question to the Trash. To make sure it will solve the problem and not ruin your system though, first see what happens if you quit the process from within Activity Monitor by clicking the X sign icon while the line of the process is selected, then choosing 'Force quit'. Or, if you're an admin (sudo rights), do it the fun way:

In Activity Monitor, find the number in the PID column for your process, let's say it's 789. Then launch Terminal and run: `sudo kill -9 789`. Sign the death contract with your login password and press enter to let the axe fall.

If the thing you want gone goes away, then go ahead and trash the file. If it doesn't, do a reboot and some more googling :)

Now, this will of course only delete the actual executable and leave any other lingering files intact.
The most common location where applications save preferences and meta-data, etc. is `~/Library/Application Support/NameOfTheApp`. The tilde (~) means your home folder, the same place where Documents, Desktop and other such folders are located. The Library folder is hidden by default though, but can be reached with that same command from Finder, shift-cmd-g. If there is a folder in Application Support with the same name as the app, go ahead and drag that to the trash as well.

Finally there are applications (and terminal commands for that matter) that will dig up and erase every last trace of a given application, but I don't have any experience with those apps and the terminal stuff is probably outside the scope of this comment... 

Now I'm off to hide those pesky default icons cluttering my menu bar, really stoked to see an open source option for this stuff! I nearly settled on the paid one that at least had public release notes, but fortunately I gave google one more shot and found Dozer :)

**Comment by gingerbeardman** [comment]
1. Quit Dozer
   - right click dot menu icon
   - click first dozer tab
   - choose quit
2. Delete app

You can optionally delete preferences or use something like App Cleaner to delete the app and associated files.

**Comment by johsoderi** [comment]
> 1. Quit Dozer
>    
>    * right click dot menu icon
>    * click first dozer tab
>    * choose Quit
> 2. Delete app
> 
> Optional: delete preferences
> 
> Or use something like App Cleaner to delete the app and associated files.

Or this, yeah.

I have no memory of writing this novel of a comment and in hindsight, a TL;DR  wouldn’t really be out of place.

**Comment by Albeppo** [comment]
Thanks a lot for your help.
I got it deleted. But in the meantime I re-installed it and now I’m a quite happy user.
Only I’m missing a drop-down for the icons in the menu bar when the menu of an application gets to broad.
Switch to a program with a shorter menu to be able to access the hidden icons is a bit cumbersome.
:-)
Wishing you all the best. Have a good time,
Ansgar

**Comment by Mortennn** [comment]
> Only I’m missing a drop-down for the icons in the menu bar when the menu of an application gets to broad.
Switch to a program with a shorter menu to be able to access the hidden icons is a bit cumbersome.
@Albeppo This gets fixed in the next update 4.2.0 :-)

**Comment by Albeppo** [comment]
Wow. That sounds fantastic. Great move. 😊

VG/BR, Ansgar 

Sent from my smart handheld
